import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClientSessionProvider } from "./components/ClientSessionProvider";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { WalletProviders } from "./walletproviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSessionProvider>
          <WalletProviders>
            <div className="min-h-screen flex flex-col bg-white">
              <Navbar />
             <main className="flex-grow">{children}</main> 
              <Footer />
            </div>
          </WalletProviders>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
